[package]
name = "learning_rust"
version = "0.1.0"
authors = ["Bijesh O S <bijesh.os@testemail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
